a = '3'
b = '4'
print(a + "+" + b + "=", str(3+4))
print(a + '-' + b + '=', str(3-4))
print(a + '/' + b + '=', str(3/4))
print(a + '*' + b + '=', str(3*4))
print(a + '**' + b + '=', str(3**4))
print(a + '%' + b + '=', str(3%4))
print(a + '//' + b + '=', str(3//4))